CREATE TABLE dive (
    _id  INTEGER PRIMARY KEY AUTOINCREMENT,
    dive_no  INTEGER NOT NULL,
    dive_date TEXT NOT NULL,
    location TEXT,
    time_in TEXT,
    duration_bottom_time INTEGER,
    duration_safety_stop INTEGER,
    tank_pressure_before REAL,
    tank_pressure_after REAL,
    depth_max REAL,
    temperature_air REAL,
    temperature_surface REAL,
    temperature_bottom REAL,
    visibility REAL,
    weight REAL,
    dive_skin INTEGER,
    wet_suit INTEGER,
    dry_suit INTEGER,
    hooded_vest INTEGER,
    gloves INTEGER,
    boots INTEGER,
    comments TEXT
)